### ISSUE TITLE
Formulation 5 in your paper

### ISSUE THREAD

**Issue by vhientran** [GeneZC/ASGCN#4]
Dear @GeneZC ,
I am sorry for disturbing you, but  I wonder about the formulation 5 about the function F() in your paper. You use this function for calculating the position-aware weight. I understand that when r+1 <= i <= r+m, q_i should be 1, instead of 0 as in your paper?
Thank you very much for your time!

**Comment by GeneZC** [comment]
We set them to 0s because we assume that aspects themselves are not clues for judging sentiment polarities, however, they indeed are supervision for retrieving clues. And in this way, we fill out the positions of aspects with features in other positions.
Also, I personally think your means is also acceptable and you could further conduct experiments on it. We will be very pleased if you do the experiments and report the results here.
Thanks for your attention.

**Comment by vhientran** [comment]
Thanks for your explanation. In your paper, you said that: "Furthermore,
following the idea of self-looping in Kipf and Welling (2017), each word is manually set adjacent to itself, i.e. the diagonal values of A are all
ones.". In case of setting q_i=0 when r+1 <= i <= r+m, I wonder that the self-loop idea is unuseful because of your position-aware weight...

**Comment by GeneZC** [comment]
Yes, exactly. It is not useful for representations of aspect terms.

**Comment by vhientran** [comment]
Now, I understand. Thanks for your help and I wish you a happy new year. Thank you.

**Comment by GeneZC** [comment]
Also wish you a happy new year !
